test: add query count check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -117,18 +117,19 @@ jobs:
           VALID_RECORD=$(kubectl exec -i deploy/postgres -- psql -U postgres -d asl -tA << 'EOF'
             SELECT COUNT(*) 
             FROM predictions
-            WHERE 
-              (status_code::numeric >= 400)
-              OR
-              (
-                ABS( 
-                  (SELECT SUM(value::numeric) FROM jsonb_each_text(all_probabilities)) - 1
-                ) < 1e-12
-              );
+            WHERE status_code = 200
+              AND ABS( 
+                (SELECT SUM(value::numeric) FROM jsonb_each_text(all_probabilities)) - 1
+              ) < 1e-5;
           EOF
           )
 
           echo "VALID_RECORD"=$VALID_RECORD
+
+          if [ "$VALID_RECORD" -ne 1 ]; then
+          echo "::error::prediction with status_code=200 and correct probabilities not found"
+          exit 1
+          fi
 
       - name: diagnostic
         if: failure()
